services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./includes:/usr/share/nginx/html/includes
      - ./shared-imgs/github.io:/usr/share/nginx/html/assets/images
