# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GH pages repo
        uses: actions/checkout@v4

      - name: Checkout shared images repo
        uses: actions/checkout@v4
        with:
          repository: factormrp/shared-imgs
          token: ${{ secrets.IMGS_PAT }}
          path: shared-imgs

      - name: Copy private images
        run: |
          mkdir -p public/assets/images
          cp -R shared-imgs/github.io/* public/assets/images/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './{public,includes}'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
